<img src="images\Logo_UCLL_ENG_RGB.png" style="background-color:white;" />

# Data Analytics & Machine learning

Lecturers: Aimée Lynn Backiel, Lies Bollens, Fien Van de Woestijne

Academic year 2026-2027

## Lab 2: Data analytics with Pandas

### Recap of last lab(s)

#### Lab 1

1. We ensured we had a valid Python installation.
2. We learnt what a virtual environment is:
   * Isolated Python executable and packages.
   * We created a virtual environment.
3. Absolute path vs relative path recap.
4. Recap of data structures in Python

#### Lab 2
1. Installed Pandas
2. Learnt how to read data
3. Learnt how to calculate mean, mode, median etc.
4. Basic exploration of the 4 variables
5. Bivariate exploration

### The case

Ada Turing Travelogue, or as everyone calls her, Ada just started working part time at her parents travel agency. She has a keen understanding and interest of everything related to applied computer science ranging from server & system management to full stack software development. Through database foundations she already understands how to query data and programming 1 and 2 covered the essentials about the Python programming language. Recently she has just decided to start learning about data analytics & machine learning as well.

She uses her skills to connect to the travel agency's database where she finds many, normalized, tables. Ada recalls what she learnt in database foundations and performs all the correct joins. Afterwards she saves the data in the `data/` folder.


She finds the following dataset:

| Column Name          | Description                                                                                       |
| -------------------- | ------------------------------------------------------------------------------------------------- |
| SalesID              | Unique identifier for each sale.                                                                  |
| Age                  | Age of the traveler.                                                                              |
| Country              | Country of origin of the traveler.                                                                |
| Membership_Status    | Membership level of the traveler in the booking system; could be 'standard', 'silver', or 'gold'. |
| Previous_Purchases   | Number of previous bookings made by the traveler.                                                 |
| Destination          | Travel destination chosen by the traveler.                                                        |
| Stay_length          | Duration of stay at the destination.                                                              |
| Guests               | Number of guests traveling (including the primary traveler).                                             |
| Travel_month         | Month in which the travel is scheduled.                                                           |
| Months_before_travel | Number of months prior to travel that the booking was made.                                       |
| Earlybird_discount   | Boolean flag indicating whether the traveler received an early bird discount.                     |
| Package_Type         | Type of travel package chosen by the traveler.                                                    |
| Cost                 | Calculated cost of the travel package.                                                            |
| Margin | The cost (for the traveler) - what the travel agency pays. |
 | Additional_Services_Cost| The amount of additional services (towels, car rentals, room service, ...) that was bought during the trip. |

### Helping Ada explore the dataset

The main goal for the remainder of this lab is to explore the data. We will specifically take five columns:

* cost
* age
* stay_length
* destination
* country

Our goal is to find interesting relationships between them.

As was covered in the book and lecture there are two main data types in analytics: categorical and numerical data. This is a crucial first step in your analysis because it determines what methods make sense on your data.

**The goal is primarily to find out what influences the cost of the stay.**

### Part 1: Recap from last week

#### Reading and exploring data: univariate

In [1]:
import pandas as pd # by convention
pd.options.display.float_format = '{:.2f}'.format

In [2]:
travel_dataset = pd.read_csv("data/lab_3_dataset.csv")

Let's have a very short refresher of last week's lab. One of the first things you typically do with a dataset is print out the first few rows.

In [3]:
travel_dataset.head()

,Unnamed: 0,sales_id,age,country,membership_status,previous_purchases,destination,stay_length,guests,travel_month,months_before_travel,earlybird_discount,package_Type,cost,rating,margin,additional_services_cost
0,0,1,47,UK,silver,1,Sydney,4,2,7,1,False,Adventure,1706.09,6,1219.74,291.06
1,1,2,37,Italy,silver,5,Tokyo,4,2,8,4,False,Adventure,281233.19,7,1570.39,405.52
2,2,3,49,USA,standard,2,Sydney,3,4,7,1,False,Cultural,2829.92,6,2360.49,285.36
3,3,4,62,Spain,silver,2,Cape Town,7,2,1,3,True,Adventure,2789.53,7,2315.66,747.53
4,4,5,36,Germany,silver,3,Paris,9,3,2,7,False,Adventure,5358.00,5,5042.14,1117.09

Accessing the columns is equally trivial.

In [4]:
travel_dataset.columns

Index(['Unnamed: 0', 'sales_id', 'age', 'country', 'membership_status',
       'previous_purchases', 'destination', 'stay_length', 'guests',
       'travel_month', 'months_before_travel', 'earlybird_discount',
       'package_Type', 'cost', 'rating', 'margin', 'additional_services_cost'],
      dtype='str')

We can also make subsets like this:

In [5]:
columns = ["country", "stay_length", "age", "cost", "destination"]
travel_dataset_subset = travel_dataset[columns]
travel_dataset_subset

        country  stay_length  age      cost destination
0            UK            4   47   1706.09      Sydney
1         Italy            4   37 281233.19       Tokyo
2           USA            3   49   2829.92      Sydney
3         Spain            7   62   2789.53   Cape Town
4       Germany            9   36   5358.00       Paris
...         ...          ...  ...       ...         ...
9995    Germany           11   59   7504.78   Cape Town
9996  Australia            6   18   1427.12      Sydney
9997        USA            5   29   3458.86       Paris
9998        USA           16   47  18392.27       Paris
9999     Canada           15   49   3041.91   Cape Town

[10000 rows x 5 columns]

##### ❓ Summarize all the numerical variables with one line of code. Write down everything you notice about the variable cost.

In [6]:
#YOUR CODE HERE
travel_dataset_subset[["age",'cost', "stay_length"]].describe()

           age        cost  stay_length
count 10000.00    10000.00     10000.00
mean     39.98   114814.74        10.49
std      14.00   457712.61         7.05
min      18.00 -1000000.00         1.00
25%      29.00     2414.47         5.00
50%      39.00     4845.14         9.00
75%      50.00    10222.98        14.00
max      80.00  6724039.17        68.00

YOUR OBSERVATIONS HERE

##### ❓ Summarize one of the categorical variables.

In [7]:
#YOUR CODE HERE
travel_dataset_subset["country"].value_counts()
# travel_dataset_subset["destination"].value_counts()

country
UK           1320
Italy        1274
USA          1267
France       1266
Spain        1265
Australia    1222
Canada       1214
Germany      1172
Name: count, dtype: int64

In [8]:
YOUR OBSERVATION HERE

SyntaxError: invalid syntax (2243929714.py, line 1)

### Part 2: Data exploration - bivariate


Now we will look at pairs of variables, to see if we find any interesting relations between two variables. This analysis takes multiple steps.
1) First, you decide which two variables might be interesting to look at together
2) Second, you have to decide upon a technique for analysis. This technique will differ depending on the type of variable. The different combinations are: two numerical variables, two categorical variables and one categorical and one numerical variable. 
3) Depending on the type of variables, you can carry out different analysis. We will explore this below, with one example for each type, to give you an idea of what different analysis looks like for different types of variables. 

Later, when you encounter two other variables you want to analyse, you can use these examples as a blueprint to start carrying out the correct analysis.

##### ❓ Which variables do you think are interesting to take a look at together?  Write a short motivation on why you would like to look at them and why you chose this technique to analyse this. Then carry out the proper analysis. Choose at least three different combinations: two categorical, two numerical, and one categorical and a numerical variable. Don't lose sight of what we are trying to figure out: what influences the cost of the stay. End your answer with what you observe from your analysis.

##### 1) Two numerical variables:
- Why do you look at them? 
- What technique do you use and why?

YOUR MOTIVATION HERE

In [ ]:
#YOUR CODE HERE
import matplotlib.pyplot as plt

plt.scatter(
    travel_dataset_subset["stay_length"],
    travel_dataset_subset["cost"]
)

plt.xlabel("Stay length")
plt.ylabel("Cost")
plt.title("Stay length vs cost")
plt.show()
travel_dataset_subset[["stay_length", "cost"]].corr()

In [ ]:
travel_dataset[["age", "cost", "stay_length"]].corr()

YOUR OBSERVATIONS HERE

##### 2) One numerical variable and one categorical variable: 

- Why do you look at them? 
- What technique do you use and why?

YOUR MOTIVATION HERE

In [ ]:
#YOUR CODE HERE
travel_dataset_subset.groupby("destination")["cost"].describe()
travel_dataset[["country", "cost"]].groupby("country").describe()

YOUR OBSERVATIONS HERE

##### 3 ) Two categorical variables:

This analysis will follow the same structure as before. Now, it's up to you to create your own markdown and code cells.

##### ❓ Extra: I'd like to study age and cost using the groupby method. Is that a good idea? Explain why or why not. If not, do you see a way to make it work?

YOUR EXPLANATION HERE

In [ ]:
#YOUR CODE SOLUTION HERE
pd.crosstab(travel_dataset["destination"], travel_dataset["country"])
# travel_dataset[["destination", "country"]].groupby(["destination", "country"]).count()

In [ ]:
travel_dataset["age_group"] = pd.cut(travel_dataset["age"], bins = [0,25,35,45,55,65,100], labels = ["under 25", "25-35", "35-45", "45-55", "55-65", "over 65"])
travel_dataset[['age_group', "cost"]].groupby("age_group").describe()

##### ❓ If you have not done so before, analyze cost per destination. Do you notice any abnormal results?

In [ ]:
#YOUR CODE HERE

YOUR OBSERVATIONS HERE

##### ❓ How would you deal with this?

YOUR ANSWER HERE

### Part 3:  Subsetting and cleaning data

Ada gets confirmation from her contacts that the data has some issues. The booking system broke down and produced large negative values. Additionally, the currency converter for Tokyo is giving incorrect results.

We will help her rectify these mistakes.

#####  Removing data: boolean indexing

Generally it's a good idea to not alter your original dataset but filter it in a copy. The way Pandas does this is by filtering with a boolean mask. We will demonstrate step by step how to do this.

<center>
<img src="https://numpy.org/doc/stable/_images/broadcasting_1.png" style="background-color:white;">
</center>

The data we want gone are the rows where the cost equals `-1000000.00`. We can check for each row if that's the case. 

Pandas uses a technique called "broadcasting" where if you try to do operations between values of different shapes Pandas will try to expand one to make them match.

This means you don't need to explicitly turn the value into an array of the same size.

In [ ]:
non_errors = travel_dataset["cost"] != -1000000.00
non_errors

❓ Check how many non_errors we have in the dataset

In [ ]:
#YOUR CODE HERE
non_errors.sum()

❓ Is explicitly checking if the cost does not equal -1000000.00 the best way to filter out wrong cost values? Adapt the checking for non_errors to a more logical constraint. See if we still have the same number of errors.

In [ ]:
#YOUR CODE HERE
non_errors = travel_dataset["cost"] >= 0

Pandas allows you to give a boolean array as an index to filter out rows. The rows where the boolean array (also known as a mask) is `True` are kept.

In [ ]:
# Valid travel cost should not be negative
non_errors = travel_dataset["cost"] >= 0
non_errors.sum()

We can also combine all of the above in one line, to directly filter out all the values with a faulty cost

In [ ]:
travel_dataset[non_errors]

##### ❓Create a new dataset called `_dataset_cleaned` , which contains only the rows with a non faulty value. Make a copy of the original dataset, such that we do not accidentally alter values in the original dataset

In [ ]:
#YOUR CODE HERE
# Keep only rows with a valid, non-negative cost
_dataset_cleaned = travel_dataset[non_errors].copy()

##### ❓ Make a mask for the people that traveled to Tokyo. Call the variable `tokyo`.

In [ ]:
#YOUR CODE HERE
# Boolean mask selecting the trips to Tokyo
tokyo = _dataset_cleaned["destination"] == "Tokyo"

#####  Updating rows the right way

We can now grab the rows where the destination is Tokyo as follows

In [ ]:
_dataset_cleaned[tokyo]

This gives us a filtered dataset of all people that traveled to Tokyo, with the faulty values already removed.
We can take a look at the cost column as follows

In [ ]:
_dataset_cleaned[tokyo]["cost"]

Now we have the rows we can convert the currency by dividing by 158, to get the correct price. 
You will likely try to do this in the following way:

`_dataset_cleaned[tokyo]["cost"] /= 158`

You can try it out below and look at the result

In [ ]:
_dataset_cleaned[tokyo]["cost"] /= 158

This gives us the same error as we encountered in the previous session. The way we can get around is is by using `data.loc`.

When we read the error message, it tells us two things: 
1) The abovementioned code currently still works in certain cases, but in the future it will not work anymore. 

*This is a sure sign that we should not use this line of code anymore. If we would, in the future, it might suddenly break and not function anymore. Right now, we know where we are coding and can easily update this line of code. But, in the future, we might have a whole project with 1000s of lines of code. If you then have to look for where exactly the error occurs, you will end up spending a long time doing something not very fun. Think about future you.*

2) to use  `df.loc[row_indexer, "col"] = values` instead, since this will ensure we **keep on updating the original dataframe**. 



`df.loc` can be quite confusing. It is an object you can slice by using square brackets `[]`. The first element is the **index**. This is typically the column on the far left.

In [ ]:
_dataset_cleaned.index # Each dataframe has an index, which is shown on the left. It typically starts at 0 and goes to the number of rows - 1.

In [ ]:
tokyo.index # Each series has an index too

In [ ]:
_dataset_cleaned.loc[tokyo] # Loc filters the dataset where tokyo is true

In [ ]:
_dataset_cleaned.loc[tokyo, "cost"]

It is a good habit to make a copy before you change your data. If you don't do this and make a mistake you need to rerun your entire script. For a small dataset like this it's not a big problem, but as you scale it can become a bottleneck.

In [ ]:
cleaned_dataset = _dataset_cleaned.copy()

In [ ]:

cleaned_dataset.loc[tokyo, "cost"] /= 158

In [ ]:
_dataset_cleaned

We can also give columns or a list of columns to `.loc`. In this case only the rows we ask for will be returned

In [ ]:
_dataset_cleaned.loc[tokyo, "cost"]

It is a good habit to make a copy before you change your data. If you don't do this and make a mistake you need to rerun your entire script. For a small dataset like this it's not a big problem, but as you scale it can become a bottleneck.


##### ❓ create a new copy of the dataset, called `cleaned_dataset`. Use the df.loc function to divide the cost of the trips to Tokyo by 158.

In [ ]:
#YOUR CODE HERE
# Make a fresh copy and correct the Tokyo costs
cleaned_dataset = _dataset_cleaned.copy()
cleaned_dataset.loc[tokyo, "cost"] /= 158

##### ❓We will briefly look at the impact of what we did on our analysis of cost by destination. What effect did our corrections have on the data?

In [ ]:
#YOUR CODE HERE
# Compare cost per destination after cleaning
cleaned_dataset.groupby("destination")["cost"].describe()

YOUR OBSERVATIONS HERE

##### ❓Compare the correlation between age, cost and stay length before and after data cleaning. What differences do you see?

In [ ]:
#YOUR CODE HERE
# Correlations before cleaning
travel_dataset[["age", "cost", "stay_length"]].corr()

In [ ]:
#YOUR CODE HERE
# Correlations after cleaning
cleaned_dataset[["age", "cost", "stay_length"]].corr()

YOUR OBSERVATION HERE


##### ❓ How do we interpret these correlations? Why do you think the correlations changed so much?

YOUR EXPLANATION HERE

Extra food for thought: 
- correlation only gives a measure of linear relationships. Low correlations don't always mean an absence of a relationship, it could be there but just non-linear.
- a correlation measures the fact that there is **a** linear relationship. However, how exactly to interpret these numbers is not necessarily straightforward. 


How do we interpret our correlation value of 0.75?

**What correlation does NOT mean**
> If variable A increases with 1 unit variable B increases with 0.75 units.

**Why is this not the interpretation?** 

The (sample) correlation $r_{X,Y}$ is given as:

$$
r_{x,y} = \frac{cov(x,y)}{(n-1)s_{x}s_{y}} = \frac{\sum_{i=1}^{n}{(x_{i} - \bar{x})(y_{i} - \bar{y})}}{(n-1)s_{x}s_{y}}
$$

We have some notation to unpack here.

We have two variables $x$ and $y$. These each have a mean $\bar{x}$ and $\bar{y}$ pronounced as x bar and y bar respectively, $s_{x}$ and $s_{y}$ are respectively the standard deviations of x and y.

The first equality shows us that the correlation $r_{x, y}$ is a normalized version of something called the covariance (cov). The scaling is achieved by dividing by a factor related to the product of the standard deviations of the two variables. This is what ensures that $r_{x,y} \in [-1, 1]$. 

Thee covariance expresses the joint variability of two variables. A covariance of 8 means that if variable x increased by 1 the other variable increases by an amount that is dependent on the units and scale of both variables; it doesn't specify a fixed number of units either.

Thus, the correct interpretation of a correlation coefficient is: 

> A correlation coefficient, measures the strength and direction of a linear relationship between two variables, but not the slope of that relationship.

Finally, to know how much one variable varies in function of the other we can look at the regression slope:

$$
\beta_{y} = r_{x,y}\frac{s_{x}}{s_{y}}
$$

The slope of the regression has a deep connection with the correlation. It's the correlation weighted by the proportion of the standard deviations. Logically, if $s_{x} = s_{y}$ the interpretation given last lecture holds. Generally that is not the case, so those that made this remark last lecture were correct. The equation above shows that it is trivial to recover the slope from the correlation.

It is important to remember that correlations and the slope of a regression are expressing linear relationships. As discussed last lecture Anscombe's quartet consists of four datasets that have nearly identical simple descriptive statistics, yet have very different distributions and appear very different when graphed. **This highlights the importance of visualizing data and not relying solely on statistical metrics.**


<center>
Anscomnbe's quarter: four datasets with an equal correlation.
<br>
<br>
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Anscombe%27s_quartet_3.svg/1200px-Anscombe%27s_quartet_3.svg.png" style="width:50%">
</center>

### Introduction to plotting with Matplotlib, Seaborn and Plotly

We have helped Ada so far to gain insights into her data by wrangling it into shape and making tables to summarize data. Now, to further enhance our understanding and visualize the patterns, trends, and potential anomalies, we will be plotting the data. 

Making data visual simplifies complex datasets and also makes it more intuitive for stakeholders to grasp key takeaways. By transitioning from tabular summaries to graphical plots, we can also communicate more effectively.

#### Matplotlib

<center>
<img src="https://matplotlib.org/stable/_images/sphx_glr_logos2_003.png" style="background-color:white">
</center>

The name matplotlib comes from matrix plotting library. It's a descendant from the MATLAB programming language. It's by now an older library (2003) that has some quirks, but it is still important to know the basics of Matplotlib since other Python plotting libraries build on top of it.

In [ ]:
# uncomment to install
#%pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt # convention

##### Plotting univariate data


The table below is a summary of the different types of plots for **numeric data**.

| Plot Type          | Description                                           | When to Use                                                      |
|--------------------|-------------------------------------------------------|------------------------------------------------------------------|
| **Histogram**      | Displays the distribution of a single continuous variable by dividing the data into bins and showing the frequency of observations in each bin. | To visualize the distribution of a variable, especially to identify its central tendency (mean), spread (standard deviation), and skewness (are low or high values more common).  |
| **Box Plot (or Whisker Plot)** | Shows the distribution of a variable using quartiles and displays potential outliers. | To get a summary of a variable's distribution in terms of its median, quartiles, and possible outliers. Useful when comparing the distribution across categories. |
| **Density Plot (or Kernel Density Plot)** | Provides a smoothed version of a histogram. | To visualize the distribution of a variable in a continuous manner. Particularly useful when comparing the distributions of multiple variables on the same plot. |
| **Violin Plot**    | Combines aspects of box plots and density plots.       | To visualize both the distribution and summary statistics of a variable. Especially useful when comparing across different categories. |

The syntax for plotting is generally `plt.<plotType>(x, y)`.

In [ ]:
plt.boxplot(cleaned_dataset["cost"]); # Matplotlib prints things while plotting, the semicolon an suppress it.

A boxplot provides a comprehensive view of a dataset's distribution, offering more detailed insights than typical tables. The central line within the box represents the median, splitting the data into its lower and upper halves. The box itself is framed by two lines: the lower boundary represents the 25th percentile (or Q1), meaning 25% of the data lies below this value, and the upper boundary denotes the 75th percentile (or Q3), indicating that 75% of the data is below this point.

The range between Q3 and Q1 is known as the Interquartile Range (IQR). Beyond the box, the plot extends 'whiskers'. Their "distance" is calculated as `1.5 * IQR` both above and below the box, providing a range for typical data points. Any data outside these whiskers can be considered possible outliers.

##### ❓ What can we learn from this boxplot? Try answering the following questions in your response:
* is the data symmetrical, or skewed? How did you see this? What does that mean for the cost variable?
* is there a large spread in the data or not? How did you see this? What does that mean for the cost variable?
* where does most of the data lie? Are there any points that differ significantly from the others?

YOUR OBSERVATIONS HERE

##### ❓Take a look at the list of possible plots above. Which one would make sense to make when we are just looking at one variable at the time? Figure out the syntax to make this plot and create one for cost.

In [ ]:
#YOUR CODE HERE
# A histogram is suitable for visualizing the distribution of one numerical variable
plt.hist(cleaned_dataset["cost"])
plt.xlabel("Cost")
plt.ylabel("Frequency")
plt.title("Distribution of travel cost")
plt.show()

If all goes well, you made a histogram in the figure above. The histogram has a parameter called 'bins'.

##### ❓Try setting bins to different values. Can you figure out what it does? Try to find a good value for bins for cost.

In [ ]:
#YOUR CODE HERE
# Try a larger number of bins to show more detail in the distribution
plt.hist(cleaned_dataset["cost"], bins=50)
plt.xlabel("Cost")
plt.ylabel("Frequency")
plt.title("Distribution of travel cost")
plt.show()

##### ❓How would you interpret this histogram? Use the same questions as with the boxplot to formulate your answer

YOUR INTERPRETATION HERE

##### ❓Now make both of these figures again for age and interpret the results. You can write one conclusion in which you discuss both plots at ones if you prefer. Make sure to describe WHAT you see and WHERE you see it on the plot. (This time, make your own code and markdown boxes again.)

For categorical data, categories can often serve as a basis for comparison in other plots, like boxplots. This means you can use a single category to differentiate data within such plots. You can also produce the same type of plot multiple times, once for each category, to analyze patterns within individual categories.


| Plot Type     | Description                                          | When to Use                                         |
|---------------|------------------------------------------------------|-----------------------------------------------------|
| **Count Plot**| Represents the frequency or count of each category.  | To see how often each category appears in the data. |

Count plots require an additional package, called seaborn. We will learn how to make plots with seaborn in the next lab.